services:
  gestion-aranceles:
    build:
      context: ./
      dockerfile: ./deploy/local/python.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - tarea-unidad-04
    depends_on:
      - mongodb

  benefits-container:
    build:
      context: ./
      dockerfile: ./deploy/local/python.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn app.benefits.main:app --reload --host 0.0.0.0 --port 8001
    networks:
      - tarea-unidad-04
    depends_on:
      - mongodb
    environment:
      - MONGO_ADMIN_USER=${MONGO_ADMIN_USER}
      - MONGO_ADMIN_PASS=${MONGO_ADMIN_PASS}
    env_file:
      - .env

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - tarea-unidad-04
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
      MONGO_INITDB_DATABASE: admin
      
    
volumes:
  mongodb-data:
networks:
  tarea-unidad-04:
    external: false
