# ConfigMap para variables de entorno no sensibles
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  RABBITMQ_URL: 'amqp://user:pass@rabbitmq:5672/'

---
# Secret (están codificadas en base64, así tiene que ir)
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGO_ADMIN_USER: YWRtaW4=
  MONGO_ADMIN_PASS: YWRtaW4=
  RABBITMQ_USER: dXNlcg==
  RABBITMQ_PASS: cGFzcw==

---
# Deployment para MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
# PVC para MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Deployment para RabbitMQ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASS

---
# Deployment para aranceles-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aranceles-app
spec:
  selector:
    matchLabels:
      app: aranceles-app
  template:
    metadata:
      labels:
        app: aranceles-app
    spec:
      containers:
        - name: gestion-aranceles
          image: tokifelipe/tarea-unidad-04:latest
          ports:
            - containerPort: 8000
          command:
            ['uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8000']
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

        - name: debt-container
          image: tokifelipe/tarea-unidad-04:latest
          ports:
            - containerPort: 8003
          command:
            ['uvicorn', 'app.debt.main:app', '--host', '0.0.0.0', '--port', '8003']
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

        - name: payment-container
          image: tokifelipe/tarea-unidad-04:latest
          ports:
            - containerPort: 8002
          command:
            ['uvicorn', 'app.payment.main:app', '--host', '0.0.0.0', '--port', '8002']
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

        - name: benefits-container
          image: tokifelipe/tarea-unidad-04:latest
          ports:
            - containerPort: 8001
          command:
            ['uvicorn', 'app.benefits.main:app', '--host', '0.0.0.0', '--port', '8001']
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

        - name: debt-consumer
          image: tokifelipe/tarea-unidad-04:latest
          command: ["python", "-m", "app.debt.consumer"]
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

        - name: payment-consumer
          image: tokifelipe/tarea-unidad-04:latest
          command: ["python", "-m", "app.payment.consumer"]
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

        - name: benefits-consumer
          image: tokifelipe/tarea-unidad-04:latest
          command: ["python", "-m", "app.benefits.consumer"]
          env:
            - name: MONGO_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_USER
            - name: MONGO_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ADMIN_PASS
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL

---
# Services
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: aranceles-app
spec:
  type: LoadBalancer
  selector:
    app: aranceles-app
  ports:
    - name: gestion-aranceles
      port: 80
      targetPort: 8000
      nodePort: 30000
    - name: debt
      port: 8003
      targetPort: 8003
      nodePort: 30003
    - name: payment
      port: 8002
      targetPort: 8002
      nodePort: 30002
    - name: benefits
      port: 8001
      targetPort: 8001
      nodePort: 30001