apiVersion: v1
kind: Service
metadata:
  name: gestion-aranceles
spec:
  type: LoadBalancer
  ports:
  - port: 80  # Cambia esto al puerto que use tu aplicación
    targetPort: 80
  selector:
    app: gestion-aranceles

